import type { AttackConfig, AttackKind } from '../shared/types';

export const playerAttacks: Record<AttackKind, AttackConfig> = {
  light1: {
    kind: 'light1',
    damage: 10,
    knockbackX: 220,
    knockbackY: 140,
    range: 58,
    height: 52,
    duration: 90,
    recovery: 115,
  },
  light2: {
    kind: 'light2',
    damage: 12,
    knockbackX: 260,
    knockbackY: 150,
    range: 64,
    height: 54,
    duration: 95,
    recovery: 125,
  },
  light3: {
    kind: 'light3',
    damage: 18,
    knockbackX: 420,
    knockbackY: 260,
    range: 74,
    height: 58,
    duration: 110,
    recovery: 180,
  },
  heavy: {
    kind: 'heavy',
    damage: 28,
    knockbackX: 520,
    knockbackY: 280,
    range: 88,
    height: 66,
    duration: 150,
    recovery: 320,
  },
  special: {
    kind: 'special',
    damage: 22,
    knockbackX: 520,
    knockbackY: 230,
    range: 104,
    height: 92,
    duration: 430,
    recovery: 260,
    specialCost: 35,
  },
};
